version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - "15672:15672"  # management port
      - "5672:5672"   # amqp port
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  redis:
    image: redis
    restart: always
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"

  worker:
    image: sztakilpds/cqueue_worker:0.2.3
    environment:
      - BROKER=amqp://guest:guest@rabbitmq:5672
      - RESULT_BACKEND=redis://redis:6379
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    depends_on:
      - frontend

  worker2:
    image: sztakilpds/cqueue_worker:0.2.3
    environment:
      - BROKER=amqp://guest:guest@rabbitmq:5672
      - RESULT_BACKEND=redis://redis:6379
    command: --batch=true
    restart: always
    depends_on:
      - frontend

  frontend:
    image: sztakilpds/cqueue_frontend:0.2.3
    environment:
      - BROKER=amqp://guest:guest@rabbitmq:5672
      - RESULT_BACKEND=redis://redis:6379
    restart: always
    ports:
      - "8080:8080"
