# build stage
FROM golang:alpine AS build-env
COPY . /src
WORKDIR /src/cmd/worker
RUN GOOS=linux go build worker.go

# final stage
FROM alpine
COPY --from=build-env /src/cmd/worker/worker /opt/
ENTRYPOINT ["/opt/worker"]

