version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - "15672:15672"  # management port
      - "5672:5672"   # amqp port
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  redis:
    image: redis
    restart: always
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    environment:
      - BROKER=amqp://guest:guest@rabbitmq:5672
      - RESULT_BACKEND=amqp://guest:guest@rabbitmq:5672
    restart: always
    depends_on:
      - frontend

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    environment:
      - BROKER=amqp://guest:guest@rabbitmq:5672
      - RESULT_BACKEND=amqp://guest:guest@rabbitmq:5672
    restart: always
    ports:
      - "8080:8080"
