# build stage
FROM golang:alpine AS build-env
COPY . /src
WORKDIR /src/cmd/frontend
RUN GOOS=linux go build frontend.go httpRouter.go

# final stage
FROM alpine
COPY --from=build-env /src/cmd/frontend/frontend /opt/
COPY ./cmd/frontend/views /opt/views/
WORKDIR /opt
ENTRYPOINT ["/opt/frontend"]
